import mongoose from 'mongoose';

const PayslipSchema = new mongoose.Schema({
  // Employee
  userId:        { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
  userIdStr:     { type: String, required: true },
  employeeName:  { type: String, required: true },
  employeeEmail: { type: String, required: true },
  department:    { type: String, default: '' },
  designation:   { type: String, default: '' },
  idCardNo:      { type: String, default: '' },
  station:       { type: String, default: '' },

  // Pay period
  payPeriod:  { type: String, required: true },   // "July 2026"
  month:      { type: String, required: true },
  year:       { type: Number, required: true },
  payDate:    { type: String, default: '' },

  // Attendance summary
  workingDaysInMonth: { type: Number, default: 0 },
  presentDays:        { type: Number, default: 0 },
  lwpDays:            { type: Number, default: 0 },
  lwpDeduction:       { type: Number, default: 0 },
  extraDays:          { type: Number, default: 0 },  // Sunday working

  // Earnings
  basic:            { type: Number, default: 0 },
  hra:              { type: Number, default: 0 },
  da:               { type: Number, default: 0 },
  specialAllowance: { type: Number, default: 0 },
  conveyance:       { type: Number, default: 0 },
  medical:          { type: Number, default: 0 },
  otherAllowances:  { type: Number, default: 0 },
  grossEarnings:    { type: Number, default: 0 },

  // Deductions
  employerPf:      { type: Number, default: 0 },
  employeePf:      { type: Number, default: 0 },
  esi:             { type: Number, default: 0 },
  professionalTax: { type: Number, default: 0 },
  tds:             { type: Number, default: 0 },
  otherDeductions: { type: Number, default: 0 },
  totalDeductions: { type: Number, default: 0 },

  // Summary
  grossSalary:  { type: Number, required: true },
  totalCtc:     { type: Number, default: 0 },
  netPay:       { type: Number, required: true },
  amountInWords:{ type: String, default: '' },

  // Generated by
  generatedBy:     { type: String, default: '' },
  generatedByName: { type: String, default: '' },

  // Disbursement
  disbursementStatus: {
    type: String,
    enum: ['draft', 'approved', 'disbursed'],
    default: 'draft'
  },
  approvedBy:    { type: String, default: '' },
  approvedAt:    { type: Date, default: null },
  disbursedBy:   { type: String, default: '' },
  disbursedAt:   { type: Date, default: null },

  // Email status
  emailStatus: {
    type: String,
    enum: ['pending', 'sent', 'failed'],
    default: 'pending'
  },
  emailSentAt: { type: Date, default: null },

}, { timestamps: true });

PayslipSchema.index({ userIdStr: 1, month: 1, year: 1 }, { unique: true });
PayslipSchema.index({ disbursementStatus: 1 });

export const Payslip = mongoose.model('Payslip', PayslipSchema);
